spring.application.name=project-backend
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=User@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.com.ecommerce=DEBUG
logging.file.name=app.log

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=b422005@iiit-bh.ac.in
spring.mail.password=hoje ujdn dljd mzig

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true